version: '3.8'

services:
  rabbitmq:
    image: 'rabbitmq:3-management'
    hostname: 'rabbitmq'
    ports:
      - '15672:15672' # RabbitMQ management interface guest:guest
      - '5672:5672'   # RabbitMQ default port

  websocket:
    build: server/.
    container_name: websocket
    command: python websocket.py
    volumes:
      - ./server:/app/
    depends_on:
      - rabbitmq
    environment:
      - RABBITMQ_URL=amqp://rabbitmq:5672
    ports:
      - '9090:9090'

  django:
    container_name: django
    build: server/.
#    command: tail -f /dev/null
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./server:/app/
    depends_on:
      - rabbitmq
    ports:
      - '8000:8000'
